### ISSUE TITLE
Nginx returning 500 Internal server error for JSON rest API

### ISSUE THREAD

**Issue by tanvir-retailai** [SpiderLabs/ModSecurity#2486]
**Describe the bug**

I implemented a REST API service. My REST API service running under nginx proxy with modsecurity. It's working fine and modsecurity also doing well. Now, all my api requests are using `Content-Type` http header parameter. All my API working pretty well if I  call the API by passing the content type as `Content-Type: application/json`. However, if I pass the content type parameter as `Content-Type: application/json; charset=utf-8` then modsecurity returning `500 - <strong>Internal server error.</strong>` to the caller and furthermore my API service still receiving  the request without the POST body (if the API is a POST API).

Here is a sample API call I used:
`curl --include --request POST --header "Content-Type: application/json; charset=utf-8" --data-binary '{"id": "test@email.com", "psw": "1234"}' 'https://myrest.service.io/v1/user/signin'`

The above request returning `500 - <strong>Internal server error.</strong>` and my API service still getting the POST body without any data. It means `modsecurity` returning a response directly to the caller immediately but keep passing the request to the downstream service by modifying POST body.

I am using default modsecurity rulesets and I found there is a rules in `modesecurity.conf` as:
`SecRule REQUEST_HEADERS:Content-Type "application/json" \
     "id:'200001',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"`

Not sure this is the problem or not because I disabled the above rule using `SecRuleRemoveById 200001` and still getting same error.

**Logs and dumps**

[modsec_debug.log](https://github.com/SpiderLabs/ModSecurity/files/5752745/modsec_debug.log)
[modsec_audit.log](https://github.com/SpiderLabs/ModSecurity/files/5752746/modsec_audit.log)

Output of:
 1. DebugLogs (level 9)
 2. AuditLogs

_Notice:_ Be carefully to not leak any confidential information.

**To Reproduce**

For my rest API service I used following curl command which is a signin API. If you noticed closely then see that I am passing `; charset=utf-8` in the Content-Type header. If I eliminate that part then `Modsecurity` is not complaining and not returning 500.

`curl --include --request POST --header "Content-Type: application/json; charset=utf-8" --data-binary '{"id": "test@email.com", "psw": "1234"}' 'https://myrest.service.io/v1/user/signin'`

**Expected behavior**

Modsecurity should not return 500  `<strong>Internal server error.</strong>` instead either 403 or a valid HTTP code because it's not an internal server error.

**Server (please complete the following information):**
 - ModSecurity version (and connector): ModSecurity v3.0.2 with with nginx-connector v1.0.1
 - WebServer: nginx/1.18.0
 - OS (and distro): Centos 7 (5.7.9-1.el7.elrepo.x86_64)

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? Yes
 - What is the version number?  [https://github.com/coreruleset/coreruleset.git](url) [v3.4/dev]

**Comment by martinhsv** [comment]
Hello @tanvir-retailai ,

I tried your test case with ModSecurity v3.0.4 but was not able to reproduce what you have reported.

At v3.0.2, the ModSecurity version that you are using is quite old.  It could be that that there is a bug in that earlier version that does not exist in current code.  My suggestion would be to try upgrading your ModSecurity to v3.0.4.

If you still experience the problem with that more recent version, including debug log output (level 9) would be helpful.

**Comment by tanvir-retailai** [comment]
@martinhsv Thanks for your reply.

I tried v3.0.4 and after running `./configure` I got following in my terminal:

```
config.status: creating examples/reading_logs_via_rule_message/Makefile
config.status: creating examples/using_bodies_in_chunks/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
 
 
ModSecurity - v3.0.4 for Linux
 
 Mandatory dependencies
   + libInjection                                  ....v3.9.2-30-gbf234eb
   + SecLang tests                                 ....c8cf2c5
 
 Optional dependencies
   + GeoIP/MaxMind                                 ....found 
      * (MaxMind) v
         /usr/local/lib/libmaxminddb.so, /usr/local/include, -DWITH_MAXMIND -I/usr/local/include
      * (GeoIP) v1.5.0
         -lGeoIP  , -I/usr/include/  
   + LibCURL                                       ....found v7.29.0 
      -lcurl  ,  -DWITH_CURL
   + YAJL                                          ....found v2.0.4
      -lyajl  , -DWITH_YAJL  
   + LMDB                                          ....disabled
   + LibXML2                                       ....found v2.9.1
      -lxml2 -lz -lm -ldl, -I/usr/include/libxml2 -DWITH_LIBXML2
   + SSDEEP                                        ....found 
      -lfuzzy -L/usr/lib64/, -DWITH_SSDEEP -I/usr/include
   + LUA                                           ....found v501
      -llua-5.1 -L/usr/lib64/, -DWITH_LUA -DWITH_LUA_5_1 -I/usr/include
 
 Other Options
   + Test Utilities                                ....enabled
   + SecDebugLog                                   ....enabled
   + afl fuzzer                                    ....disabled
   + library examples                              ....enabled
   + Building parser                               ....disabled
   + Treating pm operations as critical section    ....disabled
```

After that I run `make` and got following error:

```
 -o .libs/libmodsecurity.so.3.0.4
/bin/ld: cannot find -llibmaxminddb
collect2: error: ld returned 1 exit status
make[3]: *** [libmodsecurity.la] Error 1
make[3]: Leaving directory `/usr/local/src/ModSecurity/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/ModSecurity/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/src/ModSecurity/src'
make: *** [all-recursive] Error 1
```

I checked and confirmed that all other libraries installed properly. Any idea?

**Comment by zimmerle** [comment]
@tanvir-retailai That is happening because the libMaxMind is not on yours LD_LIBRARY_PATH. You can either install maxmind on your distribution library path, or add this new path to the list of library paths. Further info on the former - https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux

**Comment by zimmerle** [comment]
I am assuming that the problem is fixed, therefore closing this issue. if it is not the case, please re-open.

**Comment by IamLunchbox** [comment]
I have compiled libmodsecurity.so.3.0.4 and use modsecurity-nginx with the coreruleset. 

A notes app I am using via webdav (Joplin) seemed to mangle http-requests and triggered the crs:
```
B ----
PROPFIND /locks/ HTTP/1.1
depth: 1
connection: close
authorization: Basic 
Host: 
content-type: text/xml
if-none-match: JoplinIgnore-30283
user-agent: Joplin/1.0
content-length: 190
accept-encoding: gzip,deflate
accept: */*

F---
HTTP/1.1 403
Server: nginx
Date: Tue, 19 Jan 2021 15:49:49 GMT
Content-Length: 146
Content-Type: text/html
X-Content-Type-Options: nosniff
Connection: close
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Referrer-Policy: strict-origin
Strict-Transport-Security: max-age=31536000;includeSubDomains

H--
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Rx' with parameter `(?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)\s+(?:\/|\w)[^\s]*(?:\s+http\/\d|[\r\n])' against variable `REQUEST_BODY' (Value: `<?xml version="1.0" encoding="UTF-8"?>\x0a\x09\x09\x09<d:propfind xmlns:d="DAV:">\x0a\x09\x09\x09\x0 (162 characters omitted)' ) [file "/etc/nginx/modsec/coreruleset-3.3.0/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "33"] [id "921110"] [rev ""] [msg "HTTP Request Smuggling Attack"] [data "Matched Data: propfind xmlns:d="dav:">\x0a found within REQUEST_BODY: <?xml version="1.0" encoding="utf-8"?>\x0a\x09\x09\x09<d:propfind xmlns:d="dav:">\x0a\x09\x09\x09\x09<d:prop xmlns:oc="http://owncloud.org/ns">\x0a\x09\x09\x09\x09\x09<d:getlastm (57 characters omitted)"] [severity "2"] [ver "OWASP_CRS/3.3.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/33"] [hostname "94.16.107.168"] [uri "/locks/"] [unique_id "1611071389"] [ref "o45,25v298,190t:urlDecodeUni,t:htmlEntityDecode,t:lowercase"]
```
After removing rule `921110 ` via `SecRuleRemoveByID 921110` requests are not blocked by modsecurity anymore, but nginx reports an Error code 500:

```
---Njg3yJ3G---B--
PUT /locks/sync_desktop_389ee0062a2b4b27b691290045fd4e5a.json HTTP/1.1
authorization: Basic
Host: 
content-type: text/plain
if-none-match: JoplinIgnore-41747
user-agent: Joplin/1.0
content-length: 84
accept-encoding: gzip,deflate
connection: close
accept: */*

---Njg3yJ3G---D--

---Njg3yJ3G---E--
<html>\x0d\x0a<head><title>500 Internal Server Error</title></head>\x0d\x0a<body>\x0d\x0a<center><h1>500 Internal Server Error</h1></center>\x0d\x0a<hr><center>nginx</center>\x0d\x0a</body>\x0d\x0a</html>\x0d\x0a

---Njg3yJ3G---F--
HTTP/1.1 500
Server: nginx
Date: Wed, 20 Jan 2021 12:17:02 GMT
Content-Length: 170
Content-Type: text/html
X-Content-Type-Options: nosniff
Connection: close
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Referrer-Policy: strict-origin
Strict-Transport-Security: max-age=31536000;includeSubDomains
```
Disabling modsecurity altogether fixes this problem.

Enabling modsecurity without the owasp coreruleset (via modsecurity/main.conf) leads to an error 500 again (see above for the audit log). The the following configuration settings were used nginx.conf:
- load_module modules/ngx_http_modsecurity_module.so;
- modsecurity on;
- modsecurity_rules_file /etc/nginx/modsec/main.conf;

If you need a debug log let me know.

**Comment by zimmerle** [comment]
> I have compiled libmodsecurity.so.3.0.4 and use modsecurity-nginx with the coreruleset.
> 


That seems to be an issue with coreruleset. You may want to open this same issue on the CRS project.

**Comment by IamLunchbox** [comment]
The error persists even if I fully delete coreruleset. I specifically downloaded the default modsecurity.conf and unicode.mapping, the error 500 persists.

I guess Modsecurity somehow changes the http-request and Joplin fails to communicate with the server due to this - attaching to the dav and to other webservices with other clients does not reproduce the issue. Since it could be an issue solely for Joplin I think you can consider this a client side problem for Joplin and the issue for ModSecurity solved.

**Comment by zimmerle** [comment]
> The error persists even if I fully delete coreruleset. I specifically downloaded the default modsecurity.conf and unicode.mapping, the error 500 persists.
> 
> I guess Modsecurity somehow changes the http-request and Joplin fails to communicate with the server due to this - attaching to the dav and to other webservices with other clients does not reproduce the issue. Since it could be an issue solely for Joplin I think you can consider this a client side problem for Joplin and the issue for ModSecurity solved.

In that case it will be interesting to have the _debug_ and _error_ log while CRS is not loaded.

**Comment by IamLunchbox** [comment]
[nginx_debug.txt](https://github.com/SpiderLabs/ModSecurity/files/5844864/nginx_debug.txt)

This is it, I used `error_log /var/log/nginx/error.log debug;`  in nginx.conf to generate it. If that does not contain enough information, let me know. I didn't have the time to recompile nginx and libmodsecurity with the necessary flags yet.

**Comment by IamLunchbox** [comment]
Will there be a follow up regarding this issue or shall I create a separate bugreport?

**Comment by afkaraja222-crypto** [comment]
You donk
