### ISSUE TITLE
ModSecurity logs to the Windows event log with Event ID 0 instead of -1

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [SpiderLabs/ModSecurity#676]
Below is an example of a message logged by ModSecurity on Windows. To my knowledge, when the EventId is unknown, the event should be logged with EventId set to -1 (minus 1). This would probably prevent the EventId 0 cannot be found message from being logged with every message.

Example:

The description for Event ID 0 from source ModSecurity cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

_real message being logged_

**Comment by haruntmkr** [comment]
Hi,

I got same error but i didn't understand your fixing. 
Could you tell me how i can fix this error? 
Thanks your answer.

**Comment by zimmerle** [comment]
This was fixed in the code. Which version of ModSecurity are you running?

**Comment by haruntmkr** [comment]
i tried ModSecurity IIS_2.8.0-64bit and ModSecurity IIS_2.9.1-64b

**Comment by zimmerle** [comment]
The ID should be fine on 2.9.1

**Comment by haruntmkr** [comment]
I installed modsecurity version 2.9.1 64 bit but i got error

Log Name:      Application
Source:        ModSecurity
Date:          6/3/2016 3:53:36 PM
Event ID:      1
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-RNA83N2IDID
Description:
The description for Event ID 1 from source ModSecurity cannot be found. 
Either the component that raises this event is not installed on your local computer or the installation is corrupted. 
You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.


After I had gotten this error, I installed visual studio 2013 and Microsoft Visual C++ 2012 x86 and x64. I didn't install anything else. I still get error. How can i fix that?

**Comment by dmz006** [comment]
I am using 2.9.1 and still receive the message about "ModSecurity cannot be found".

It appears this has been an issue for a while as I also see it mentioned in #647 and #877 and and #910

**Comment by ghost-atl** [comment]
Issue closed, with no solution? I don't understand!!!

**Comment by csanders-git** [comment]
@ghost-atl the general method is that after there is a response we *think* solves the problem we close the ticket. If the issue isn't solved successfully the party should reopen it. Although there really should only be one ticket for this problem if it is a bug.

**Comment by haruntmkr** [comment]
I think it was general notification on Modsecurity. I changed hole rule , configuration , version didn't notice anything. I realized when i attack my web site, modsecurity give an error so this log cause attack.

**Comment by ghost-atl** [comment]
I've tried to get this rule to write something in the log but it doesn't log or deny anything. 
SecRule ARGS, "zzz" phase:1,log,deny,status:503,id:1
